#include <stdio.h>
#include <riscv.h>
#include <syscall.h>
#include <stdlib.h>
#include <string.h>
//#include <fs.h>
#include <syscall.h>
#include <queue.h>
#include <process.h>
#include <memory.h>
#include <prototypes.h>